export const formats = [
  'YYYY-MM-DD',
  'DD/MM/YYYY',
  'MM/DD/YYYY',
  'YYYY-MM-DD HH:mm',
  'DD/MM/YYYY HH:mm',
  'DD.MM.YYYY HH:mm',
  'DD.MM.YYYY',
  'MM/DD/YYYY HH:mm',
  'YYYY/MM/DD HH:mm',
  'YYYY-MM-DD HH:mm:ss',
  'DD/MM/YYYY HH:mm:ss',
  'MM/DD/YYYY HH:mm:ss',
  'YYYY/MM/DD HH:mm:ss',
  'YYYY-MM-DDTHH:mm:ssZ',
  'YYYY-MM-DDTHH:mm:ss.SSSZ',
  'ddd MMM DD YYYY HH:mm:ss [GMT]ZZ',
  'ddd, DD MMM YYYY HH:mm:ss [GMT]ZZ',
  'YYYY-MM-DDTHH:mm:ss.SSS',
  'YYYY-MM-DDTHH:mm:ss',
  'YYYY-MM-DDTHH:mm',
  'HH:mm:ss',
  'hh:mm:ss A',
  'MMM DD, YYYY',
  'D MMM YYYY',
  'MMMM DD, YYYY',
  'DD MMMM YYYY',
  'MMM DD, YYYY HH:mm',
  'D MMM YYYY HH:mm',
  'MMMM DD, YYYY HH:mm',
  'DD MMMM YYYY HH:mm',
  'MMM DD, YYYY HH:mm:ss',
  'D MMM YYYY HH:mm:ss',
  'MMMM DD, YYYY HH:mm:ss',
  'DD MMMM YYYY HH:mm:ss',
  'dddd, MMMM Do YYYY, h:mm:ss a',
  'dddd, MMMM Do YYYY, h:mm a',
  'MMM DD YYYY',
  'DD MMM YYYY',
  'D/M/YYYY',
  'D.M.YYYY',
  'M/D/YYYY',
  'M.D.YYYY',
  'YYYY/MM/DD HH:mm:ss.SSS',
  'MM/DD/YYYY h:mm A',
  'MM/DD/YYYY hh:mm A',
  'MM/DD/YYYY h:mm:ss A',
  'MM/DD/YYYY hh:mm:ss A',
  'MM/DD/YY h:mm A',
  'MM/DD/YY hh:mm A',
  'MM/DD/YY h:mm:ss A',
  'MM/DD/YY hh:mm:ss A',
  'YYYY/MM/DD hh:mm A',
  'YYYY/MM/DD h:mm A',
  'YYYY/MM/DD hh:mm:ss A',
  'YYYY/MM/DD h:mm:ss A',
  'YYYY-MM-DD HH:mm:ss.SSSZ',
  'MMM D, YYYY',
  'ddd, D MMM YYYY',
  'MMM D, YYYY h:mm A',
  'ddd, D MMM YYYY h:mm A',
  'MMM D, YYYY h:mm:ss A',
  'ddd, D MMM YYYY h:mm:ss A',
  'MMMM Do, YYYY',
  'D MMMM, YYYY',
  'MMMM Do, YYYY h:mm A',
  'D MMMM, YYYY h:mm A',
  'MMMM Do, YYYY h:mm:ss A',
  'D MMMM, YYYY h:mm:ss A',
  'YYYY/MM/DD',
  'YYYY/MM',
  'MMM YYYY',
  'MMMM YYYY'
];
